"""Stable categorical values for news and event contracts."""

from enum import StrEnum


class NewsSourceType(StrEnum):
    """Kinds of providers from which raw news may be observed."""

    FINANCIAL_NEWS = "FINANCIAL_NEWS"
    WIRE = "WIRE"
    SEC = "SEC"
    COMPANY_RELEASE = "COMPANY_RELEASE"
    MACRO_CALENDAR = "MACRO_CALENDAR"
    CENTRAL_BANK = "CENTRAL_BANK"
    GOVERNMENT = "GOVERNMENT"
    GLOBAL_NEWS = "GLOBAL_NEWS"
    SOCIAL = "SOCIAL"
    SPECULATIVE = "SPECULATIVE"
    OTHER = "OTHER"


class EventType(StrEnum):
    """Stable top-level canonical event taxonomy."""

    COMPANY = "COMPANY"
    SECTOR = "SECTOR"
    MACRO = "MACRO"
    GEOPOLITICAL = "GEOPOLITICAL"
    REGULATORY = "REGULATORY"
    MARKET_STRUCTURE = "MARKET_STRUCTURE"
    SYSTEMIC = "SYSTEMIC"
    COMMODITY = "COMMODITY"
    CURRENCY = "CURRENCY"
    RATE = "RATE"


class EventSubtype(StrEnum):
    """Small namespaced deterministic canonical-event subtype taxonomy."""

    COMPANY_EARNINGS = "COMPANY.EARNINGS"
    COMPANY_GUIDANCE = "COMPANY.GUIDANCE"
    COMPANY_MERGER_ACQUISITION = "COMPANY.MERGER_ACQUISITION"
    COMPANY_PRODUCT = "COMPANY.PRODUCT"
    COMPANY_MANAGEMENT = "COMPANY.MANAGEMENT"
    COMPANY_LEGAL = "COMPANY.LEGAL"
    COMPANY_SEC_FILING = "COMPANY.SEC_FILING"
    COMPANY_CAPITAL_RAISE = "COMPANY.CAPITAL_RAISE"
    COMPANY_BUYBACK = "COMPANY.BUYBACK"
    COMPANY_DIVIDEND = "COMPANY.DIVIDEND"
    COMPANY_OTHER = "COMPANY.OTHER"

    SECTOR_OTHER = "SECTOR.OTHER"

    MACRO_CPI = "MACRO.CPI"
    MACRO_JOBS = "MACRO.JOBS"
    MACRO_GDP = "MACRO.GDP"
    MACRO_RETAIL_SALES = "MACRO.RETAIL_SALES"
    MACRO_OTHER = "MACRO.OTHER"

    RATE_CENTRAL_BANK_DECISION = "RATE.CENTRAL_BANK_DECISION"
    RATE_CENTRAL_BANK_SPEECH = "RATE.CENTRAL_BANK_SPEECH"
    RATE_OTHER = "RATE.OTHER"

    REGULATORY_ANTITRUST = "REGULATORY.ANTITRUST"
    REGULATORY_APPROVAL = "REGULATORY.APPROVAL"
    REGULATORY_ENFORCEMENT = "REGULATORY.ENFORCEMENT"
    REGULATORY_EXPORT_CONTROL = "REGULATORY.EXPORT_CONTROL"
    REGULATORY_OTHER = "REGULATORY.OTHER"

    GEOPOLITICAL_CONFLICT = "GEOPOLITICAL.CONFLICT"
    GEOPOLITICAL_SANCTION = "GEOPOLITICAL.SANCTION"
    GEOPOLITICAL_TRADE_RESTRICTION = "GEOPOLITICAL.TRADE_RESTRICTION"
    GEOPOLITICAL_ELECTION = "GEOPOLITICAL.ELECTION"
    GEOPOLITICAL_OTHER = "GEOPOLITICAL.OTHER"

    MARKET_STRUCTURE_OTHER = "MARKET_STRUCTURE.OTHER"

    SYSTEMIC_BANK_FAILURE = "SYSTEMIC.BANK_FAILURE"
    SYSTEMIC_EXCHANGE_OUTAGE = "SYSTEMIC.EXCHANGE_OUTAGE"
    SYSTEMIC_MARKET_DISRUPTION = "SYSTEMIC.MARKET_DISRUPTION"
    SYSTEMIC_OTHER = "SYSTEMIC.OTHER"

    COMMODITY_OTHER = "COMMODITY.OTHER"
    CURRENCY_OTHER = "CURRENCY.OTHER"

    @property
    def event_type(self) -> EventType:
        """Return the top-level type encoded by this namespaced subtype."""
        namespace, _, _ = self.value.partition(".")
        return EventType(namespace)

    @property
    def is_other(self) -> bool:
        """Return whether this is the conservative fallback for its type."""
        return self.value.endswith(".OTHER")


class EventState(StrEnum):
    """Lifecycle states for a canonical event."""

    NEW = "NEW"
    DEVELOPING = "DEVELOPING"
    CONFIRMED = "CONFIRMED"
    UPDATED = "UPDATED"
    RESOLVED = "RESOLVED"
    RETRACTED = "RETRACTED"


class ExposureRelationType(StrEnum):
    """How an event is related to an exposed instrument."""

    DIRECT_COMPANY = "DIRECT_COMPANY"
    COMPETITOR = "COMPETITOR"
    CUSTOMER = "CUSTOMER"
    SUPPLIER = "SUPPLIER"
    SECTOR = "SECTOR"
    INDUSTRY = "INDUSTRY"
    COUNTRY = "COUNTRY"
    COMMODITY = "COMMODITY"
    MACRO = "MACRO"
    REGULATORY = "REGULATORY"
    OTHER = "OTHER"
