"""Normalized market events and deterministic order-book reconstruction."""

from sra_nexus.market_data.book import OrderBook, OrderState, SequenceTracker
from sra_nexus.market_data.enums import (
    AggressorSide,
    BookAction,
    BookDataMode,
    BookSide,
    MarketEventFlag,
    MarketEventKind,
)
from sra_nexus.market_data.events import BookEvent, MarketEvent, QuoteEvent, TradeEvent
from sra_nexus.market_data.exceptions import (
    BookNotInitializedError,
    BookStreamMismatchError,
    CrossedBookError,
    DuplicateOrderError,
    DuplicateSequenceError,
    MarketDataError,
    NegativeDepthError,
    OrderAttributeMismatchError,
    OrderBookStateError,
    QuantityExceedsRemainingError,
    SequenceError,
    SequenceGapError,
    SequenceRegressionError,
    TickAlignmentError,
    UnknownOrderError,
    UnsupportedBookModeError,
)
from sra_nexus.market_data.features import (
    WeightedDepthConfig,
    calculate_microprice,
    calculate_midprice,
    calculate_order_book_imbalance,
    calculate_spread,
    calculate_weighted_depth,
    is_tick_aligned,
)
from sra_nexus.market_data.snapshots import BookSnapshot, PriceLevel

__all__ = [
    "AggressorSide",
    "BookAction",
    "BookDataMode",
    "BookEvent",
    "BookNotInitializedError",
    "BookSide",
    "BookSnapshot",
    "BookStreamMismatchError",
    "CrossedBookError",
    "DuplicateOrderError",
    "DuplicateSequenceError",
    "MarketDataError",
    "MarketEvent",
    "MarketEventFlag",
    "MarketEventKind",
    "NegativeDepthError",
    "OrderAttributeMismatchError",
    "OrderBook",
    "OrderBookStateError",
    "OrderState",
    "PriceLevel",
    "QuantityExceedsRemainingError",
    "QuoteEvent",
    "SequenceError",
    "SequenceGapError",
    "SequenceRegressionError",
    "SequenceTracker",
    "TickAlignmentError",
    "TradeEvent",
    "UnknownOrderError",
    "UnsupportedBookModeError",
    "WeightedDepthConfig",
    "calculate_microprice",
    "calculate_midprice",
    "calculate_order_book_imbalance",
    "calculate_spread",
    "calculate_weighted_depth",
    "is_tick_aligned",
]
